services:
  app:
    environment:
      OTEL_ENABLED: "true"
      OTEL_SERVICE_NAME: nest-template-monolith
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
    networks:
      observability:
        aliases:
          - nest-template-monolith

networks:
  observability:
    name: templates-observability
    external: true
